### ISSUE TITLE
BrainVision OffLineDataProvider - missing metadata

### ISSUE THREAD

**Issue by lvareka** [NEUROINFORMATICS-GROUP-FAV-KIV-ZCU/Basil_BCI#1]
When running from TestController, sampling rate and channel names are unavailable when requested.

**Comment by ProkopTomas** [comment]
Metadata - sampling frequency, channel names, etc. were moved to IBuffer and now are added to every data packaged picked from the buffer. It can be accessed by calling GetMetadata() method of IBuffer or DataPackage. 

Issue is fixes and closed.
